#This is the one that updates the site every time the new daily file is downloaded

name: daily_update
#on:
#  workflow_run:
#    workflows: ["fetch_daily"]
#    types:
#      - completed

on: workflow_dispatch
 
env: 
    SECRET: ${{ secrets.SHINYAPPS_SECRET_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3'
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: |
          any::rsconnect
          any::shiny
          any::dplyr
          any::ggplot2
    - name: Install Curl
      run: sudo apt-get install libcurl4-openssl-dev
    #- name: Install R libraries
    #  run: |
    #    install.packages(c("rsconnect", "shiny", "dplyr", "ggplot2", "lifecycle", "scales"), dependencies=TRUE)
    #  shell: Rscript {0}
    - name: Push to site
      run: Rscript bin/upload_to_site.R "$SECRET"
