name: Deploy to shinyapps.io
on: [push]
uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
  with:
  appDir: # optional
  appFiles: # optional
  appFileManifest: # optional
  appName: get_rikers_to_3300
  logLevel: # optional, default is normal
  accountName: charlesfainlehman
  accountToken: 6EA6B48E0C14C5CC47C55277A75548C3
  accountSecret: DRPZxMJmXfgUhK4HdUlBgbuGBQ8k28zk74k0ETV0
