name: update_site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - name: Install dependencies
      run: |
        install.packages("rsconnect", quiet = T)
      shell: Rscript {0}
    - name: Push to site
      run: Rscript bin/upload_to_site.R