name: update_site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3'
    - name: Install dependencies
      run: |
        install.packages("rsconnect")
      shell: Rscript {0}
#    - name: Push to site
#      run: Rscript bin/upload_to_site.R